[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
rootDirectory = "backend"

[deploy]
startCommand = "/app/project-mirror-backend"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
